### ISSUE TITLE
Toggle blue bit does not work

### ISSUE THREAD

**Issue by Reblax** [HactarCE/Colorized-CA#1]
The collision of photons shown in construction-stamps.rle that is supposed to toggle the blue bit does not work as intended.
This
![image](https://user-images.githubusercontent.com/31586672/114024701-a82bc080-9874-11eb-832e-45d38a0e5f9a.png)
Becomes this.
![image](https://user-images.githubusercontent.com/31586672/114024768-ba0d6380-9874-11eb-8863-22593144c4c1.png)

However, this configuration works to toggle the blue bit:
![image](https://user-images.githubusercontent.com/31586672/114025042-fccf3b80-9874-11eb-9294-6b1cb9abd585.png)
becomes this
![image](https://user-images.githubusercontent.com/31586672/114025011-f4770080-9874-11eb-9ad6-b910ceaf6f13.png)

It is only the photon collision that does not work.

Is the rule broken or is there another photon collision that can toggle the blue bit?

**Comment by HactarCE** [comment]
Thank you for the report! This does seem to be a bug in the rule, caused by a conflicting reaction related to memory read/write. I've changed the green cell there to cyan, and everything appears to work now.
